#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Build the display-name fonts in packages/fonts/name-fonts/.

Every font comes from google/fonts at one pinned commit and is checked against the sha256 recorded
in name-fonts.lock.json. Fonts whose licence declares a Reserved Font Name are only converted to
WOFF2; OFL clause 3 would otherwise require renaming them. The others are pinned to one weight when
they are variable, and CJK/Hangul faces are split into unicode-range chunks so a name only fetches
the glyphs it uses.
"""

from __future__ import annotations

import argparse
import io
import json
import os
import re
import shutil
import sys
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.ttLib import woff2
from fontTools.varLib.instancer import instantiateVariableFont

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_fonts import (  # noqa: E402
    CHUNK_TARGET_BYTES,
    PACKAGE_ROOT,
    REPO_ROOT,
    SPDX_CSS_HEADER,
    _http_get,
    calibrate_chunk_size,
    format_unicode_range,
    parse_unicode_range,
    plan_chunks,
    sha256_bytes,
    subset_face,
)

SOURCE_REPOSITORY = "google/fonts"
SOURCE_COMMIT = "23e54b51ddffbc7713c583748e3bd86f62b1fa4a"
RAW_BASE = f"https://raw.githubusercontent.com/{SOURCE_REPOSITORY}/{SOURCE_COMMIT}"

OUT_ROOT = PACKAGE_ROOT / "name-fonts"
FILES_DIR = OUT_ROOT / "files"
LICENSES_DIR = OUT_ROOT / "licenses"
STYLESHEET = "name-fonts.css"
MANIFEST = "manifest.json"
NOTICE = "NOTICE.md"
LOCK_PATH = Path(__file__).resolve().parent / "name-fonts.lock.json"
CONSTANTS_PATH = REPO_ROOT / "packages" / "constants" / "src" / "NameStyleConstants.ts"
OFL_BODY_SOURCE = PACKAGE_ROOT / "LICENSE-IBM-PLEX.txt"

GENERATED_HEADER = "Generated by tools/fonts/build_name_fonts.py. Do not edit by hand."
PINNED_WEIGHT = 600

# id -> script chips shown in the picker. The thresholds read the font's character map.
LATIN = {ord(c) for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"}
TURKISH = {ord(c) for c in "ÇçĞğİıÖöŞşÜü"}
LATIN_EXT = TURKISH | {
    ord(c)
    for c in "ĄąĆćĘęŁłŃńŚśŹźŻżČčĎďĚěŇňŘřŠšŤťŮůŽžÁáÉéÍíÓóÚúÑñÀàÈèÂâÊêÎîÔôÛûÄäËëÏïÿßŐőŰűĀāĒēĪīŪū"
}
CYRILLIC = set(range(0x0410, 0x0450)) | {0x0401, 0x0451}
GREEK = set(range(0x0391, 0x03A2)) | set(range(0x03A3, 0x03AA)) | set(range(0x03B1, 0x03CA))
VIETNAMESE = {
    ord(c)
    for c in "ĂăÂâĐđÊêÔôƠơƯưẠạẢảẤấẦầẨẩẪẫẬậẮắẰằẲẳẴẵẶặẸẹẺẻẼẽẾếỀềỂểỄễỆệỈỉỊịỌọỎỏỐốỒồỔổỖỗỘộỚớỜờỞởỠỡỢợỤụỦủỨứỪừỬửỮữỰựỲỳỴỵỶỷỸỹ"
}
ARABIC = set(range(0x0621, 0x063B)) | set(range(0x0641, 0x064B))
HEBREW = set(range(0x05D0, 0x05EB))
THAI = set(range(0x0E01, 0x0E2F))
DEVANAGARI = set(range(0x0905, 0x093A))
KANA = set(range(0x3041, 0x3097)) | set(range(0x30A1, 0x30FB))
HANGUL = set(range(0xAC00, 0xD7A4))
HAN = set(range(0x4E00, 0xA000))
HAN_SIMPLIFIED = {ord(c) for c in "们这个国说时会对着过发还问两门车东长马鸟鱼见吗呢吧哦啦"}
HAN_TRADITIONAL = {ord(c) for c in "們妳嗎嘛喔囉啦裡麼這說時會對著過發還問兩門車東長馬鳥魚見"}


def share(cmap: set[int], wanted: set[int]) -> float:
    return len(cmap & wanted) / len(wanted)


SCRIPT_TESTS = {
    "latin": lambda c: share(c, LATIN) >= 0.98,
    "latin_ext": lambda c: TURKISH <= c and share(c, LATIN_EXT) >= 0.9,
    "cyrillic": lambda c: share(c, CYRILLIC) >= 0.97,
    "greek": lambda c: share(c, GREEK) >= 0.97,
    "vietnamese": lambda c: share(c, VIETNAMESE) >= 0.95,
    "arabic": lambda c: share(c, ARABIC) >= 0.9,
    "hebrew": lambda c: share(c, HEBREW) >= 0.95,
    "thai": lambda c: share(c, THAI) >= 0.95,
    "devanagari": lambda c: share(c, DEVANAGARI) >= 0.95,
    "japanese": lambda c: share(c, KANA) >= 0.95 and share(c, HAN) >= 0.2,
    "korean": lambda c: share(c, HANGUL) >= 0.2,
    "chinese_simplified": lambda c: share(c, HAN_SIMPLIFIED) >= 0.9 and share(c, HAN) >= 0.25,
    "chinese_traditional": lambda c: share(c, HAN_TRADITIONAL) >= 0.9 and share(c, HAN) >= 0.25,
}
CHUNKED_SCRIPTS = frozenset({"japanese", "korean", "chinese_simplified", "chinese_traditional"})
CATEGORIES = ("sans", "serif", "display", "handwriting", "pixel", "mono")


@dataclass(frozen=True)
class NameFont:
    id: str
    label: str
    category: str
    directory: str
    file: str


# Static families: the file closest to weight 600, ties to the lighter one (small sizes stay legible).
FONTS: tuple[NameFont, ...] = (
    NameFont("noto-sans", "Noto Sans", "sans", "ofl/notosans", "NotoSans[wdth,wght].ttf"),
    NameFont("nunito", "Nunito", "sans", "ofl/nunito", "Nunito[wght].ttf"),
    NameFont("rubik", "Rubik", "sans", "ofl/rubik", "Rubik[wght].ttf"),
    NameFont("poppins", "Poppins", "sans", "ofl/poppins", "Poppins-SemiBold.ttf"),
    NameFont("space-grotesk", "Space Grotesk", "sans", "ofl/spacegrotesk", "SpaceGrotesk[wght].ttf"),
    NameFont("exo-2", "Exo 2", "display", "ofl/exo2", "Exo2[wght].ttf"),
    NameFont("comfortaa", "Comfortaa", "display", "ofl/comfortaa", "Comfortaa[wght].ttf"),
    NameFont("righteous", "Righteous", "display", "ofl/righteous", "Righteous-Regular.ttf"),
    NameFont("audiowide", "Audiowide", "display", "ofl/audiowide", "Audiowide-Regular.ttf"),
    NameFont("bangers", "Bangers", "display", "ofl/bangers", "Bangers-Regular.ttf"),
    NameFont("pacifico", "Pacifico", "handwriting", "ofl/pacifico", "Pacifico-Regular.ttf"),
    NameFont("lobster", "Lobster", "handwriting", "ofl/lobster", "Lobster-Regular.ttf"),
    NameFont("caveat", "Caveat", "handwriting", "ofl/caveat", "Caveat[wght].ttf"),
    NameFont("dancing-script", "Dancing Script", "handwriting", "ofl/dancingscript", "DancingScript[wght].ttf"),
    NameFont("playfair-display", "Playfair Display", "serif", "ofl/playfairdisplay", "PlayfairDisplay[wght].ttf"),
    NameFont("cinzel", "Cinzel", "serif", "ofl/cinzel", "Cinzel[wght].ttf"),
    NameFont("press-start-2p", "Press Start 2P", "pixel", "ofl/pressstart2p", "PressStart2P-Regular.ttf"),
    NameFont("vt323", "VT323", "pixel", "ofl/vt323", "VT323-Regular.ttf"),
    NameFont("jetbrains-mono", "JetBrains Mono", "mono", "ofl/jetbrainsmono", "JetBrainsMono[wght].ttf"),
    NameFont("m-plus-rounded-1c", "M PLUS Rounded 1c", "sans", "ofl/mplusrounded1c", "MPLUSRounded1c-Medium.ttf"),
    NameFont("zen-maru-gothic", "Zen Maru Gothic", "sans", "ofl/zenmarugothic", "ZenMaruGothic-Medium.ttf"),
    NameFont("klee-one", "Klee One", "handwriting", "ofl/kleeone", "KleeOne-SemiBold.ttf"),
    NameFont("do-hyeon", "Do Hyeon", "display", "ofl/dohyeon", "DoHyeon-Regular.ttf"),
    NameFont("black-han-sans", "Black Han Sans", "display", "ofl/blackhansans", "BlackHanSans-Regular.ttf"),
    NameFont("gowun-dodum", "Gowun Dodum", "sans", "ofl/gowundodum", "GowunDodum-Regular.ttf"),
    NameFont("zcool-kuaile", "ZCOOL KuaiLe", "display", "ofl/zcoolkuaile", "ZCOOLKuaiLe-Regular.ttf"),
    NameFont("ma-shan-zheng", "Ma Shan Zheng", "handwriting", "ofl/mashanzheng", "MaShanZheng-Regular.ttf"),
    NameFont("lxgw-wenkai-tc", "LXGW WenKai TC", "handwriting", "ofl/lxgwwenkaitc", "LXGWWenKaiTC-Bold.ttf"),
    NameFont("cairo", "Cairo", "sans", "ofl/cairo", "Cairo[slnt,wght].ttf"),
    NameFont("kanit", "Kanit", "sans", "ofl/kanit", "Kanit-SemiBold.ttf"),
    NameFont("reem-kufi", "Reem Kufi", "display", "ofl/reemkufi", "ReemKufi[wght].ttf"),
    NameFont("gfs-didot", "GFS Didot", "serif", "ofl/gfsdidot", "GFSDidot-Regular.ttf"),
    NameFont("kelly-slab", "Kelly Slab", "serif", "ofl/kellyslab", "KellySlab-Regular.ttf"),
)

ID_PATTERN = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")


def css_family(font: NameFont) -> str:
    return f"NameFont-{font.id}"


def ofl_body() -> str:
    text = OFL_BODY_SOURCE.read_text()
    start = text.index("-----------------------------------------------------------\nSIL OPEN FONT LICENSE")
    return text[start:]


def license_header(text: str) -> str:
    return text.split("PREAMBLE", 1)[0]


def reserved_font_name(text: str) -> str | None:
    header = " ".join(license_header(text).split())
    match = re.search(r"Reserved Font Names?\s+(.+?)(?:\.\s|$|This Font Software)", header)
    return match.group(1).strip().rstrip(".") if match else None


def fetch(cache: Path, rel: str, allow_missing: bool = False) -> bytes | None:
    dest = cache / SOURCE_COMMIT / rel
    if dest.is_file():
        return dest.read_bytes()
    try:
        blob = _http_get(f"{RAW_BASE}/{rel}")
    except Exception as error:  # noqa: BLE001 - reported with the path
        if allow_missing and "404" in str(error):
            return None
        raise SystemExit(f"download failed for {rel}: {error}") from error
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(blob)
    return blob


def license_text(cache: Path, font: NameFont, sfnt: bytes) -> tuple[str, str | None]:
    rel = f"{font.directory}/OFL.txt"
    blob = fetch(cache, rel, allow_missing=True)
    if blob is not None:
        return blob.decode("utf-8-sig").replace("\r\n", "\n"), rel
    # A few families ship without OFL.txt; the font's own name table states the licence.
    parsed = TTFont(io.BytesIO(sfnt), lazy=True)
    names = parsed["name"]
    description = names.getDebugName(13) or ""
    if "Open Font License, Version 1.1" not in description:
        raise SystemExit(f"{font.id}: no OFL.txt and the name table does not state OFL 1.1")
    copyright_line = names.getDebugName(0) or ""
    text = (
        f"{copyright_line}\n\n"
        "This Font Software is licensed under the SIL Open Font License, Version 1.1.\n"
        "This license is copied below, and is also available with a FAQ at:\n"
        "https://openfontlicense.org\n\n\n"
        f"{ofl_body()}"
    )
    return text, None


# Japanese fonts often draw Cyrillic and Greek full-width; those letters do not read as names.
WIDTH_SAMPLES = {
    "latin": "abcdefghijklmnopqrstuvwxyz",
    "cyrillic": "абвгдежзийклмнопрстуфхцчшщъыьэюя",
    "greek": "αβγδεζηθικλμνξοπρστυφχψω",
}
MAX_WIDTH_VS_LATIN = 1.4


def median_width(font: TTFont, text: str) -> float | None:
    cmap = font.getBestCmap()
    widths = sorted(font["hmtx"][cmap[ord(c)]][0] for c in text if ord(c) in cmap)
    return widths[len(widths) // 2] if widths else None


def coverage(font: TTFont) -> list[str]:
    cmap = set(font.getBestCmap())
    scripts = [script for script, test in SCRIPT_TESTS.items() if test(cmap)]
    latin = median_width(font, WIDTH_SAMPLES["latin"])
    for script in ("cyrillic", "greek"):
        width = median_width(font, WIDTH_SAMPLES[script])
        if script in scripts and latin and width and width > latin * MAX_WIDTH_VS_LATIN:
            scripts.remove(script)
    return scripts


def woff2_unchanged(sfnt: bytes) -> bytes:
    source = io.BytesIO(sfnt)
    out = io.BytesIO()
    woff2.compress(source, out)
    return out.getvalue()


def instance_at_pinned_weight(sfnt: bytes) -> tuple[bytes, str]:
    font = TTFont(io.BytesIO(sfnt), recalcTimestamp=False)
    limits = {}
    for axis in font["fvar"].axes:
        if axis.axisTag == "wght":
            limits["wght"] = min(max(PINNED_WEIGHT, axis.minValue), axis.maxValue)
        else:
            limits[axis.axisTag] = axis.defaultValue
    static = instantiateVariableFont(font, limits, updateFontNames=False)
    static["OS/2"].usWeightClass = int(limits["wght"])
    buffer = io.BytesIO()
    static.save(buffer)
    pins = ", ".join(f"{tag}={value:g}" for tag, value in sorted(limits.items()))
    return buffer.getvalue(), pins


def to_woff2(sfnt: bytes) -> bytes:
    font = TTFont(io.BytesIO(sfnt), lazy=True, recalcTimestamp=False, recalcBBoxes=False)
    font.flavor = "woff2"
    buffer = io.BytesIO()
    font.save(buffer)
    return buffer.getvalue()


def _chunk_job(job: tuple[str, tuple[int, ...]]) -> bytes:
    path, codepoints = job
    return subset_face(Path(path).read_bytes(), codepoints)


def cmap_of(blob: bytes) -> set[int]:
    return set(TTFont(io.BytesIO(blob), lazy=True).getBestCmap())


@dataclass
class Built:
    font: NameFont
    upstream: str
    upstream_sha256: str
    license_upstream: str | None
    license_text: str
    reserved_name: str | None
    scripts: list[str]
    weight: str
    treatment: str
    files: list[tuple[str, bytes, list[int]]]  # (path under files/, woff2, codepoints)


def build_font(font: NameFont, cache: Path, stage: Path, pool: ProcessPoolExecutor | None, lock: dict) -> Built:
    rel = f"{font.directory}/{font.file}"
    sfnt = fetch(cache, rel)
    digest = sha256_bytes(sfnt)
    locked = lock.get("fonts", {}).get(font.id, {})
    if locked.get("upstream") == rel and locked.get("upstreamSha256") not in (None, digest):
        raise SystemExit(f"{font.id}: {rel} does not match the sha256 in {LOCK_PATH.name}")
    text, license_rel = license_text(cache, font, sfnt)
    reserved = reserved_font_name(text)
    source = TTFont(io.BytesIO(sfnt), lazy=True)
    cmap = set(source.getBestCmap())
    scripts = coverage(source)
    variable = "fvar" in source
    base = f"{font.id}/{font.id}"

    if reserved:
        # OFL clause 3: a Modified Version may not use the reserved name, so this file is only
        # repackaged. Variable fonts keep their axis and declare its weight range.
        blob = woff2_unchanged(sfnt)
        if cmap_of(blob) != cmap:
            raise SystemExit(f"{font.id}: WOFF2 conversion changed the character map")
        if variable:
            axis = next(a for a in source["fvar"].axes if a.axisTag == "wght")
            weight = f"{axis.minValue:g} {axis.maxValue:g}"
        else:
            weight = "100 900"
        return Built(font, rel, digest, license_rel, text, reserved, scripts, weight,
                     "WOFF2 conversion only (reserved font name)", [(f"{base}.woff2", blob, sorted(cmap))])

    steps = []
    if variable:
        sfnt, pins = instance_at_pinned_weight(sfnt)
        steps.append(f"instanced at {pins}")
        if set(TTFont(io.BytesIO(sfnt), lazy=True).getBestCmap()) != cmap:
            raise SystemExit(f"{font.id}: instancing changed the character map")

    if not CHUNKED_SCRIPTS & set(scripts):
        steps.append("WOFF2")
        return Built(font, rel, digest, license_rel, text, None, scripts, "100 900",
                     ", ".join(steps), [(f"{base}.woff2", to_woff2(sfnt), sorted(cmap))])

    static_path = stage / f"{font.id}.ttf"
    static_path.write_bytes(sfnt)
    ordered = sorted(cmap)
    per_chunk, _ = calibrate_chunk_size(sfnt, ordered, CHUNK_TARGET_BYTES)
    plan = plan_chunks(cmap, per_chunk)
    jobs = [(str(static_path), chunk) for chunk in plan]
    blobs = list(pool.map(_chunk_job, jobs)) if pool else [_chunk_job(job) for job in jobs]
    files = []
    covered: set[int] = set()
    for index, (chunk, blob) in enumerate(zip(plan, blobs)):
        chunk_cmap = cmap_of(blob)
        if chunk_cmap != set(chunk):
            raise SystemExit(f"{font.id}: chunk {index} character map drifted from the plan")
        covered |= chunk_cmap
        files.append((f"{base}.{index:03d}.woff2", blob, sorted(chunk_cmap)))
    if covered != cmap:
        raise SystemExit(f"{font.id}: chunks do not cover the whole character map")
    steps.append(f"split into {len(files)} unicode-range chunks, WOFF2")
    return Built(font, rel, digest, license_rel, text, None, scripts, "100 900", ", ".join(steps), files)


def render_stylesheet(built: list[Built]) -> str:
    rules = [SPDX_CSS_HEADER, f"/* {GENERATED_HEADER} */", ""]
    for item in built:
        for path, _, codepoints in item.files:
            rules.append(
                "@font-face {\n"
                f"\tfont-family: '{css_family(item.font)}';\n"
                f"\tsrc: url('./files/{path}') format('woff2');\n"
                f"\tfont-weight: {item.weight};\n"
                "\tfont-style: normal;\n"
                "\tfont-display: swap;\n"
                f"\tunicode-range: {format_unicode_range(codepoints)};\n"
                "}"
            )
    return "\n".join(rules) + "\n"


def render_manifest(built: list[Built]) -> str:
    return json.dumps(
        {
            "_comment": f"{GENERATED_HEADER} Paths are relative to packages/fonts/name-fonts/.",
            "fonts": [
                {
                    "id": item.font.id,
                    "label": item.font.label,
                    "category": item.font.category,
                    "family": css_family(item.font),
                    "scripts": item.scripts,
                    "license": f"licenses/{item.font.id}.txt",
                }
                for item in built
            ],
        },
        ensure_ascii=False,
        indent="\t",
    ) + "\n"


def render_notice(built: list[Built]) -> str:
    lines = [
        "# Display-name font licences",
        "",
        f"<!-- {GENERATED_HEADER} -->",
        "",
        "Every font in `files/` is licensed under the SIL Open Font License, Version 1.1. Each",
        "font's copyright notice and licence text are in `licenses/<id>.txt` and accompany it.",
        "",
        f"Source: https://github.com/{SOURCE_REPOSITORY} at commit `{SOURCE_COMMIT}`.",
        "",
        "Fonts with a Reserved Font Name are not modified: they are only converted to WOFF2 and",
        "keep their original names. The other fonts are Modified Versions: variable fonts were",
        f"instanced at weight {PINNED_WEIGHT}, and CJK and Hangul fonts were split into subsets.",
        "Their name records are unchanged.",
        "",
        "| Font | Source file | Reserved Font Name | Treatment |",
        "| --- | --- | --- | --- |",
    ]
    for item in built:
        lines.append(
            f"| {item.font.label} | `{item.upstream}` | {item.reserved_name or '—'} | {item.treatment} |"
        )
    return "\n".join([*lines, ""])


def render_outputs(built: list[Built]) -> dict[str, bytes]:
    outputs = {
        STYLESHEET: render_stylesheet(built).encode(),
        MANIFEST: render_manifest(built).encode(),
        NOTICE: render_notice(built).encode(),
    }
    for item in built:
        outputs[f"licenses/{item.font.id}.txt"] = item.license_text.encode()
    for item in built:
        for path, blob, _ in item.files:
            outputs[f"files/{path}"] = blob
    return outputs


def existing_outputs() -> set[str]:
    if not OUT_ROOT.is_dir():
        return set()
    return {str(p.relative_to(OUT_ROOT)) for p in OUT_ROOT.rglob("*") if p.is_file()}


def check_config() -> None:
    ids = [font.id for font in FONTS]
    if len(set(ids)) != len(ids):
        raise SystemExit("duplicate name font ids")
    for font in FONTS:
        if not ID_PATTERN.fullmatch(font.id):
            raise SystemExit(f"{font.id}: ids are lowercase words joined by '-'")
        if font.category not in CATEGORIES:
            raise SystemExit(f"{font.id}: unknown category {font.category!r}")


def constants_ids() -> list[str]:
    text = CONSTANTS_PATH.read_text()
    match = re.search(r"export const NAME_FONT_IDS = \[(.*?)\] as const;", text, re.S)
    if not match:
        raise SystemExit(f"{CONSTANTS_PATH.relative_to(REPO_ROOT)}: NAME_FONT_IDS not found")
    return re.findall(r"'([a-z0-9-]+)'", match.group(1))


def build(cache: Path, workers: int) -> int:
    check_config()
    lock = json.loads(LOCK_PATH.read_text()) if LOCK_PATH.is_file() else {}
    stage = cache / "name-fonts-stage"
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)
    built: list[Built] = []
    pool = ProcessPoolExecutor(max_workers=workers) if workers > 1 else None
    try:
        for font in FONTS:
            item = build_font(font, cache, stage, pool, lock)
            size = sum(len(blob) for _, blob, _ in item.files)
            print(
                f"{font.id:20} {len(item.files):3} file(s) {size / 1024:8.1f} KiB  "
                f"{','.join(item.scripts)}  [{item.treatment}]"
            )
            built.append(item)
    finally:
        if pool:
            pool.shutdown()
    shutil.rmtree(stage)

    outputs = render_outputs(built)
    for rel in sorted(existing_outputs() - set(outputs)):
        (OUT_ROOT / rel).unlink()
    for rel, blob in outputs.items():
        dest = OUT_ROOT / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        if not dest.is_file() or dest.read_bytes() != blob:
            dest.write_bytes(blob)
    for directory in sorted(OUT_ROOT.rglob("*"), reverse=True):
        if directory.is_dir() and not any(directory.iterdir()):
            directory.rmdir()

    new_lock = {
        "_comment": f"{GENERATED_HEADER} --verify checks packages/fonts/name-fonts/ against it offline.",
        "source": {"repository": SOURCE_REPOSITORY, "commit": SOURCE_COMMIT},
        "fonts": {
            item.font.id: {
                "upstream": item.upstream,
                "upstreamSha256": item.upstream_sha256,
                "license": item.license_upstream or "composed from the name table (no OFL.txt upstream)",
                "reservedFontName": item.reserved_name,
                "treatment": item.treatment,
                "files": [f"files/{path}" for path, _, _ in item.files],
            }
            for item in built
        },
        "outputs": {rel: sha256_bytes(blob) for rel, blob in sorted(outputs.items())},
    }
    LOCK_PATH.write_text(json.dumps(new_lock, indent="\t", ensure_ascii=False) + "\n")
    total = sum(len(blob) for rel, blob in outputs.items() if rel.startswith("files/"))
    print(f"wrote {OUT_ROOT.relative_to(REPO_ROOT)}/ ({total / 1024 / 1024:.1f} MiB of fonts) and {LOCK_PATH.name}")
    return verify()


FACE_RULE = re.compile(r"@font-face\s*\{(?P<body>[^}]*)\}")


def verify() -> int:
    if not LOCK_PATH.is_file():
        raise SystemExit(f"missing {LOCK_PATH}; run the build first")
    check_config()
    lock = json.loads(LOCK_PATH.read_text())
    failures: list[str] = []

    if lock["source"] != {"repository": SOURCE_REPOSITORY, "commit": SOURCE_COMMIT}:
        failures.append("the lock was built from a different source commit; rebuild")
    recorded = lock["outputs"]
    on_disk = existing_outputs()
    for extra in sorted(on_disk - set(recorded)):
        failures.append(f"name-fonts/{extra} is not recorded in {LOCK_PATH.name}")
    for rel, digest in recorded.items():
        path = OUT_ROOT / rel
        if not path.is_file():
            failures.append(f"name-fonts/{rel} is recorded in {LOCK_PATH.name} but missing")
        elif sha256_bytes(path.read_bytes()) != digest:
            failures.append(f"name-fonts/{rel}: sha256 does not match {LOCK_PATH.name}")

    config_ids = [font.id for font in FONTS]
    if list(lock["fonts"]) != config_ids:
        failures.append("the lock's fonts differ from the FONTS list; rebuild")
    manifest = json.loads((OUT_ROOT / MANIFEST).read_text()) if (OUT_ROOT / MANIFEST).is_file() else {"fonts": []}
    manifest_ids = [entry["id"] for entry in manifest["fonts"]]
    if manifest_ids != config_ids:
        failures.append("manifest.json ids differ from the FONTS list; rebuild")
    if constants_ids() != config_ids:
        failures.append(
            f"NAME_FONT_IDS in {CONSTANTS_PATH.relative_to(REPO_ROOT)} must list the same ids in the same order"
        )
    for entry in manifest["fonts"]:
        if not (OUT_ROOT / entry["license"]).is_file():
            failures.append(f"{entry['id']}: licence file {entry['license']} is missing")
        unknown = set(entry["scripts"]) - set(SCRIPT_TESTS)
        if unknown:
            failures.append(f"{entry['id']}: unknown script ids {sorted(unknown)}")

    css_path = OUT_ROOT / STYLESHEET
    faces = [m.group("body") for m in FACE_RULE.finditer(css_path.read_text())] if css_path.is_file() else []
    families = {entry["family"]: entry["id"] for entry in manifest["fonts"]}
    ranges: dict[str, set[int]] = {}
    referenced: set[str] = set()
    for body in faces:
        props = dict(
            (key.strip(), value.strip())
            for key, _, value in (line.strip().rstrip(";").partition(":") for line in body.splitlines())
            if key.strip()
        )
        family = props.get("font-family", "").strip("'")
        src = re.search(r"url\('\./(?P<path>[^']+)'\)", props.get("src", ""))
        if family not in families:
            failures.append(f"{STYLESHEET}: face for unknown family {family!r}")
            continue
        if not src:
            failures.append(f"{STYLESHEET}: {family} face without a url")
            continue
        referenced.add(src.group("path"))
        if not (OUT_ROOT / src.group("path")).is_file():
            failures.append(f"{STYLESHEET}: {src.group('path')} does not exist")
        declared = parse_unicode_range(props.get("unicode-range", ""))
        if ranges.setdefault(family, set()) & declared:
            failures.append(f"{STYLESHEET}: {family} has overlapping unicode-range faces")
        ranges[family] |= declared
        reserved = lock["fonts"][families[family]]["reservedFontName"]
        if reserved and len(lock["fonts"][families[family]]["files"]) != 1:
            failures.append(f"{family}: a reserved-name font must ship as one unmodified file")
    fonts_on_disk = {rel for rel in on_disk if rel.startswith("files/")}
    for stray in sorted(fonts_on_disk - referenced):
        failures.append(f"name-fonts/{stray} is not referenced by {STYLESHEET}")
    for family in families:
        if family not in ranges:
            failures.append(f"{STYLESHEET}: no faces for {family}")

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}")
        return 1
    print(f"name fonts OK: {len(config_ids)} fonts, {len(fonts_on_disk)} files match {LOCK_PATH.name}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the display-name fonts in packages/fonts/name-fonts/.")
    parser.add_argument("--verify", action="store_true", help="offline: check the checked-in tree against the lock")
    parser.add_argument(
        "--cache-dir",
        type=Path,
        default=Path(__file__).resolve().parent / ".cache",
        help="where upstream downloads are kept (default: tools/fonts/.cache, git-ignored)",
    )
    parser.add_argument("--workers", type=int, default=min(8, os.cpu_count() or 1), help="parallel chunk builds")
    args = parser.parse_args()
    if args.verify:
        return verify()
    return build(args.cache_dir.resolve(), max(1, args.workers))


if __name__ == "__main__":
    sys.exit(main())
